language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite
  - TESTER_PHP_BIN=php
  - TESTER_PHP_BIN=php-cgi

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
    - php: hhvm-nightly
    - env: DB=pgsql
    - env: DB=sqlite
  exclude:
    - php: hhvm
      env: TESTER_PHP_BIN=php-cgi
    - php: hhvm-nightly
      env: TESTER_PHP_BIN=php-cgi

script:
  - vendor/bin/tester tests -p $TESTER_PHP_BIN -s -c tests/php.ini
  - php code-checker/src/code-checker.php -d app

after_failure:
  # Print *.log content
  - for i in $(find log -name \*.log); do echo "--- $i"; cat $i; echo; echo; done
  - cat app/config/config.local.neon; echo; echo;

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -e 'create database blog_test;'; fi"
  - composer selfupdate
  - composer install --prefer-dist --no-dev
  - php www/index.php root blog_test
  - composer create-project nette/code-checker code-checker ~2.2 --no-interaction --prefer-source