language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite
  - TESTER_PHP_BIN=php
  - TESTER_PHP_BIN=php-cgi

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
    - php: hhvm-nightly
    - env: DB=pgsql
    - env: DB=sqlite
  exclude:
    - php: hhvm
      env: TESTER_PHP_BIN=php-cgi
    - php: hhvm-nightly
      env: TESTER_PHP_BIN=php-cgi

script:
  - vendor/bin/tester tests -p $TESTER_PHP_BIN -s -c tests/php.ini
  - php code-checker/src/code-checker.php

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -e 'create database zeminem;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -D zeminem < sql/mysql.sql; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then echo \"{doctrine:{host:127.0.0.1,port:3306,user:root,password:'',dbname:zeminem,driver:pdo_mysql}}\" > app/config/config.local.neon fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database zeminem;' -U postgres; fi"
  - composer selfupdate
  - composer install --prefer-dist --no-dev
  - composer create-project nette/code-checker code-checker ~2.2 --no-interaction --prefer-source

#TODO: before_script - generovat pomoci prikazu, nepouzivat SQL dumpy (Doctrine)