language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
    - php: hhvm-nightly
    - env: DB=pgsql
    - env: DB=sqlite
  exclude:
    - php: hhvm
    - php: hhvm-nightly
  include:
    - php: hhvm
      script: vendor/bin/tester -p php tests -s -c tests/php.ini
    - php: hhvm-nightly
      script: vendor/bin/tester -p php tests -s -c tests/php.ini

script: vendor/bin/tester tests -s -c tests/php.ini

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -e 'create database zeminem;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -D zeminem < sql/mysql.sql; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then echo '{doctrine: {host: 127.0.0.1, port: 3306, user: root, password: \'\', dbname: zeminem, driver: pdo_mysql}}' > app/config/config.local.neon fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database zeminem;' -U postgres; fi"
  - composer selfupdate
  - composer install --prefer-dist --no-dev

#TODO: before_script - generovat pomoci prikazu, nepouzivat SQL dumpy (Doctrine)