language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

env:
  matrix:
    - DB=mysql
    - DB=pgsql

matrix:
  allow_failures:
    - env: DB=pgsql
    - php: 7.0
    - php: hhvm
    - php: hhvm-nightly

script:
  - vendor/bin/tester tests -p php -s -c tests/php.ini

after_failure:
  - cat app/config/config.local.neon;
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -e 'create database blog_mysql;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database blog_pgsql;' -U postgres; fi"
  - composer selfupdate
  - composer install --no-interaction --prefer-dist --no-progress
  - npm install -g bower
  - bower install
  - sh -c "if [ '$DB' = 'mysql' ]; then php www/index.php -u root -n blog_mysql; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then php www/index.php -u postgres -n blog_pgsql -d pgsql; fi"

notifications:
  email: false
