- name: install latest MySQL 56
  yum: name=mysql56-server state=latest

- name: ensure MySQL is running
  service:
    name: mysqld
    state: running
    enabled: yes # whether the service should start on boot

#http://stackoverflow.com/questions/17173972/how-do-you-add-swap-to-an-ec2-instance
#https://www.digitalocean.com/community/tutorials/how-to-configure-virtual-memory-swap-file-on-a-vps
# sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
# sudo /sbin/mkswap /var/swap.1
# sudo chmod 600 /var/swap.1
# sudo /sbin/swapon /var/swap.1
