---

- name: install latest Nginx
  yum: name=nginx state=latest

- name: add expires.conf
  template: src=etc/nginx/expires.conf dest=/etc/nginx/expires.conf

- name: add site config file (nginx.conf)
  template: src=etc/nginx/nginx.conf dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: start Nginx
  service:
    name: nginx
    state: started
    enabled: yes # whether the service should start on boot

...
