---

#- name: remove original Nginx files
#  file: state=absent path={{ install_dir }}

- name: ensure clone destination exists
  file: state=directory path={{ install_dir }}

- name: clone repository
  git:
    repo=https://github.com/mrtnzlml/zlml.cz.git
    dest={{ install_dir }}
    recursive=yes
    force=yes
    depth=1
  register: git_result

- name: make log dir writable
  file: state=directory path={{ install_dir }}/log mode=0777

- name: ensure temp dir exists
  file: state=directory path={{ install_dir }}/temp mode=0777

- name: clear cache directory
  when: git_result.changed
  file: path={{ install_dir }}/temp/cache state=absent

- name: install composer packages
  when: git_result.changed
  composer:
    working_dir: '{{ install_dir }}'
    no_dev: no

- name: create configuration
  template: src=usr/share/nginx/html/config/config.local.neon dest=/usr/share/nginx/html/config/config.local.neon

- name: create directory for Bower components
  file: state=directory path={{ install_dir }}/vendor-client

- name: install Bower dependencies
  bower: path={{ install_dir }}

- name: create temp directory for Webloader
  file: state=directory path={{ install_dir }}/www/webtemp mode=a+w

...
