---

- name: install PHP7 with modules
  yum: name={{ item }} state=latest
  with_items:
    - php70
    - php70-fpm       # PHP FastCGI Process Manager
    - php70-mysqlnd   # a module for PHP applications that use MySQL databases
    - php70-pdo       # a database access abstraction module for PHP applications

- name: start FPM
  service: name=php-fpm state=restarted

...
