---

- name: configure and deploy the webservers and application code
  hosts: amazon-webservers
  become: yes
  gather_facts: False
  roles:
    - common
    - webservers

#- name: deploy database server #FIXME: migrace!
#  hosts: amazon-dbservers

...
