---

- name: configure and deploy the webservers and application code
  hosts: amazon-webservers
  become: yes
  gather_facts: True # needed for ansible_os_family and so on
  roles:
    - common
    - webservers
    - dbservers

...
